### ISSUE TITLE
Can't pass Room Setup

### ISSUE THREAD

**Issue by Setadokalo** [ShootingKing-AM/PhoneVR#24]
Once the driver is set up, SteamVR requires Room Setup, but the fake headset can't pass it.

**Comment by ShootingKing-AM** [comment]
Hi @DarkEnchanter1, What exactly is not working ? Where are you getting stuck ? Whats your VR Setup are you using PhoneVR alone or with anyother controllers ?

**Comment by DarkEnchanter1** [comment]
Just PhoneVR alone, at least for now. PhoneVR does manage to connect to the phone and expose it as a headset to SteamVR, but PhoneVR can't pass the (required) room setup step, since there are no base stations to calibrate with. (For reference, other tools like iVRy just blast through this step, probably just returning constant false positives)

**Comment by ShootingKing-AM** [comment]
I still dont get you, What do you mean you "can't pass thorugh", Just Choose "Standing" -> "Calibrate Headset" -> Set the Height Setting -> Done. ez.

**Comment by DarkEnchanter1** [comment]
![image](https://user-images.githubusercontent.com/29683020/90688609-51656e00-e234-11ea-9c4c-ee245c3a554a.png)
Can't continue past the first step of Standing set up because the headset is 'not visible'.

**Comment by ShootingKing-AM** [comment]
Oh! I see, can you share these log files (https://github.com/ShootingKing-AM/PhoneVR#issues)

**Comment by DarkEnchanter1** [comment]
[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5100264/pvrlog.txt)
[steamvr.vrsettings.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5100266/steamvr.vrsettings.txt)
[pvrlog.android.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5100273/pvrlog.android.txt)
[vrcmd output.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5100277/vrcmd.output.txt)

**Comment by ShootingKing-AM** [comment]
The logs are saying that there is a connectivity issues between windows and your mobile device. Windows driver installation is perfect but the mobile device is not discoverable on network. For now, there is strict sequence of startup. Just to confirm that you exactly did the same, I want to confirm the steps. 

```To play, first open the Phone App(SteamVR should also be closed), then run the game of your choice on PC. (Obviously, both PC and Mobile should be on same Network, preferably Wifi 5.0)```

Also I would like to know which version of Windows and Android you are using. Anyways, Thanks for testing ☺️

**Comment by thezofx** [comment]
PR #28 Tries to fix this issue, please try and let us know. Thanks.
