### ISSUE TITLE
HMD Not Found

### ISSUE THREAD

**Issue by andrewgerm** [ShootingKing-AM/PhoneVR#26]
Hi
I've been trying to get PhoneVR working, but Steam VR does not see any HMD. I've just downloaded all the latest files again, and once again followed all steps.

Once I follow all steps, start the phone app, and then run a VR app on the PC, Steam says the HMD is missing. From there, I have been unable to move forward. 

Log files attached.

To recreate, I just followed the instructions given.
I have used "auto" and manually input the IP for the PC, with same results.
I tested using the Windows Mixed Reality for SteamVR (although things never got to a stage where I could actually start setup or see this)

Windows 10, fully updated.
Android 9.10 fully updated.
Steam fully updated

"D:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64\vrcmd.exe"
VR_Init failed with VRInitError_Init_HmdNotFound

[steamvr-vrsettings.zip](https://github.com/ShootingKing-AM/PhoneVR/files/5145199/steamvr-vrsettings.zip)
[vrserver.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5145201/vrserver.txt)
[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5145202/pvrlog.txt)
[pvrsettings-json.zip](https://github.com/ShootingKing-AM/PhoneVR/files/5145204/pvrsettings-json.zip)

PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : JNI startAnnouncer: :33333
PVR-JNI-I : JNI stopAnnouncer
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : JNI startAnnouncer: :33333
PVR-JNI-I : TCP error: Bad address
PVR-JNI-I : [PVRStartAnnouncer] caught Exception: send_to: Operation not permitted
PVR-JNI-I : JNI stopAnnouncer
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : JNI startAnnouncer: :33333
PVR-JNI-I : TCP error: Bad address
PVR-JNI-I : JNI stopAnnouncer
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : JNI startAnnouncer: :33333
PVR-JNI-I : TCP error: Bad address
PVR-JNI-I : JNI stopAnnouncer
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : JNI startAnnouncer: :33333
PVR-JNI-I : [PVRStartAnnouncer] caught Exception: send_to: Network is unreachable
PVR-JNI-I : JNI stopAnnouncer
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : JNI startAnnouncer: 192.168.0.16:33333
PVR-JNI-I : TCP error: Bad address
PVR-JNI-I : JNI stopAnnouncer
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : --------------------------------------------------------------------------------
PVR-JNI-I : JNI setExtDirectory: len: 60, copdstr: /storage/emulated/0/Android/data/viritualisres.phonevr/files
PVR-JNI-I : JNI startAnnouncer: 192.168.0.16:33333
PVR-JNI-I : JNI stopAnnouncer

**Comment by ShootingKing-AM** [comment]
Hello, 
The installation seems perfect, but in steamvr log, it shows,
`Sat Aug 29 2020 14:14:25.696 - error VRInitError_Init_HmdNotFound when initing driver holographic from D:\Program Files (x86)\Steam\steamapps\common\MixedRealityVRDriver\bin\win64\driver_holographic.dll.`

To find out whether its PhoneVR or Mixed reality or other or cumulative driver issue, can you try turning off all other addons from `SteamVR` -> `Startup \ Shutdown` -> `Manage Addons`, Turn off all except `PVRServer`.

What is the network topography, like How is Windows connected to Android ?

**Comment by andrewgerm** [comment]
The only other item / add-on was a gamepad, but I have disabled that (and removed it from the PC)
Still the same issue (let me know should you need any log files again)
PVRServer is now the only thing running there.

The phone has no other apps running at the same time (it's a pretty clean install.

Network topography is PC with Windows plugged into GB switch
Android phone connected via WiFi to AP that is connected directly to switch. The AP is a few metres away, so strong signal.

**Comment by ShootingKing-AM** [comment]
Did you try the latest release ? Some changes were made in Android app just yesterday.

**Comment by andrewgerm** [comment]
I have updated beta34 to beta36, first fully removing all files on the PC and phone, and then installing from scratch.

One item that might help others, is that I disabled WiFI+ on the phone, so that the device will remain connected to the chosen WiFi AP, and not try look for a mobile data connection (this is a feature that tries to ensure you always have a decent data connection, but would hinder applications that require remaining on the same network)

I however am having the exact issues as the OP above, with no change.

Should you require any logs or other info, please let me know. I am happy to try help / test.
Please provide the Discord server link.

**Comment by ShootingKing-AM** [comment]
Discord [link](https://discord.gg/pNYtBNk) is on the Readme.md itself. Can you attach the same set of logs for beta36 ? 

We have actually successfully tested well for both Android 7 + Android 10 on Windows10, with the same network topography as you have.
Anyways, Thanks for taking intrest in this project !

**Comment by andrewgerm** [comment]
PC: Windows 10 64 bit Home. Latest non-insider build (RTX 2060 6GB, Intel 9700K, 16GB RAM)
Phone: Android 9.1.0 (latest security patches)
Steam: Latest non-beta version
PhoneVR is installed to the default location. Steam is on D drive.

I have joined the DIscord, and will keep watch for updates, and install those as they arrive. Thank you

Logs / Error output:

"D:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64\vrcmd.exe"
VR_Init failed with VRInitError_Init_HmdNotFound

(There is an additional letter "c" in your Issues help text)
[android-apk-log.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5146918/android-apk-log.txt)


[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5146904/pvrlog.txt)


[steamvr-vrsettings.zip](https://github.com/ShootingKing-AM/PhoneVR/files/5146902/steamvr-vrsettings.zip)
[vrserver.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5146903/vrserver.txt)

**Comment by ShootingKing-AM** [comment]
Thanks for the logs. Unfortunately, the logs look fine except windows unable to receive "AdditionalDataMsg" from Android. Android logs show that its running as it should. I added extra networking logs in [latest ](https://github.com/ShootingKing-AM/PhoneVR/releases/latest) release. Can you try the latest version and get me the same set of logs ? 

Networking problems are little hard to narrow down ^^' and You dont need to specify any IP in Android app, it should auto detect. If these logs also will not give us any clue we need to capture entire network packets.

PS: aah that 'c' will be fixed in next readme update. Thanks !

**Comment by andrewgerm** [comment]
I have tried again with the latest uploads, and with another Android 10.1 phone. Same result.
Log files and errors below.

I am going to do some additional checking on the network here, in case there is a firewall or security item blocking things, either on the PC, phone, AP or switch (not that there should be, to my knowledge)

Same install process as last times, with nothing new, other than new files, and trying the additional phone.
Both phones, when tested, can see between PC and phone. I tried auto IP on the phone app, as well as setting it manually (the PC has a static assigned address)

VRCMD:
VR_Init failed with VRInitError_Init_HmdNotFound

[phoneapp.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5150745/phoneapp.txt)
[steamvr-settings.zip](https://github.com/ShootingKing-AM/PhoneVR/files/5150752/steamvr-settings.zip)
[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5150753/pvrlog.txt)

[vrserver.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5150760/vrserver.txt)

**Comment by ShootingKing-AM** [comment]
Thanks for the logs. Unfortunately, the logs still show normal behaviour. I didnt think it would come this far but, could you help us with network packets?

Heres how to capture network packets:
1. Download and install [winshark](https://www.wireshark.org/#download).

2. Select your *Ethernet/Wifi/working-network-interface*.
[Support Img](https://pasteboard.co/JoWh5zo.png)

3. Type the *filter* to capture PVR network packets: `udp.port==33333 ||  tcp.port==33333  || udp.port == 15243 ||  tcp.port == 15243 ||  udp.port == 51423 || tcp.port == 51423` and press enter.
[Support Img](https://pasteboard.co/JoWhfS6.png)

4. Open *PVR App on Android, Open SteamVR on Windows, Try to connect both*.
5. Close both Android App and SteamVR.

6. Stop network capture by pressing the red button below menu bar.
[Support Img](https://pasteboard.co/JoWhpEQ.png)
7. Goto File->Save. And upload the `.pcapng` file along with logs (just released a [new beta version](https://github.com/ShootingKing-AM/PhoneVR/releases/latest))

**Comment by andrewgerm** [comment]
I updated my Wireshark, and ran the requested captures. And no packets at all.
This was run with current Windows settings, and then with the firewall disabled for the same test.

I have also updated PhoneVR to the latest, as of today.

"D:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64\vrcmd.exe
VR_Init failed with VRInitError_Init_HmdNotFound

Logs attached below:

[steamvr-settings.zip](https://github.com/ShootingKing-AM/PhoneVR/files/5178028/steamvr-settings.zip)
[vrserver.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5178029/vrserver.txt)
[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5178030/pvrlog.txt)
[phonevr-ap-log.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5178038/phonevr-ap-log.txt)

**Comment by TrickPlayzMC** [comment]
I have the same issue

**Comment by thezofx** [comment]
> I have the same issue

It would be more helpful if you raise a separate issue for it, with much more detailed explanation along with some logs.

**Comment by ShootingKing-AM** [comment]
> I updated my Wireshark, and ran the requested captures. And no packets at all.
> This was run with current Windows settings, and then with the firewall disabled for the same test.
> 
> I have also updated PhoneVR to the latest, as of today.
> 
> "D:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64\vrcmd.exe
> VR_Init failed with VRInitError_Init_HmdNotFound
> 
> Logs attached below:
> 
> [steamvr-settings.zip](https://github.com/ShootingKing-AM/PhoneVR/files/5178028/steamvr-settings.zip)
> [vrserver.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5178029/vrserver.txt)
> [pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5178030/pvrlog.txt)
> [phonevr-ap-log.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5178038/phonevr-ap-log.txt)

I see. There are some apps which work like wireshark to capture network packets on Andorid. Can you try one of those to get the android <kbd>pcap</kbd> file ? (my recommendation is to use [`tPacketCapture`](https://play.google.com/store/apps/details?id=jp.co.taosoftware.android.packetcapture&hl=en_IN)) We actually can know if the android app is sending the broadcast messages or not.

*Steps for tPacketCapture:*
1. Install the app, Give it required permissions (vpn, etc..)
2. Start the app, Click "Capture".
3. Minimize `tPacketCapture`, Start `PhoneVR` Android app, just try to establish connection.
4. Stop PhoneVR. Stop tPacketCapture (as per its instructions)(if it still is not stopping, like in my case, force close the tPacketCapture application)
5. Upload the <kbd>pcap</kbd> file here. You can find it in `Filelist` tab of tPacketCapture app.

Thanks.

**Comment by andrewgerm** [comment]
Attached is the pcap file as requested.
Again, please note, this phone has no other apps / data on it, and no SIM card, and is running Android 9.

While I have tested PhoneVR on another phone with SIM and Android 10.1, I did have the same error, so have continued to test on an older phone, as the main one is used daily for work.

I will also be checking firmware on the local WiFi AP / switch, in case that is causing an issue (I need to update firmware on here in any case)

[2020_09_06_153354.zip](https://github.com/ShootingKing-AM/PhoneVR/files/5179716/2020_09_06_153354.zip)

**Comment by ShootingKing-AM** [comment]
@andrewgerm The android <kbd>pcap</kbd> shows that `PVR Android app` is sending broadcast packets as it should. There is certain mechanism or firewall on switch or wifiap which is blocking the `broadcast` and not relaying them to your PC(since you have tried switching off your Windows' firewall already, ruling out possibility of PC Firewall/AV).

Can still help you further, but you will have to specify some details about the switch and wifiap, like, make, model, version and specific config you might be using (like NAT, etc etc)

Other than this project, have you used any application which uses Server/Client model between your Mobile and PC ? Like FTP servers, HTTP servers, Data sharing between Mobile/PC without use of Internet, etc etc ?

**Comment by andrewgerm** [comment]
HI :)
I have and do use several services between PC and that mobile (and my main one). Including testing mobiles sites on a webserver here (connected to the same switch, internal IMAP, media streaming, etc.)

But after all you have said, and what I am seeing myself, I am having doubts about that AP. It might take a few days, but I will swap that AP and switch out of the connection between everything, and test again.

I was doing some checking of the firmware on the AP last night, and I'm starting to think there is an issue there. I had disabled the firewall as a test on there too, with same results. And there is no NAT, and all these are still behind my main router.

I shall post results back here soon, in the hopes this helps you or others with the same issue.

**Comment by ShootingKing-AM** [comment]
Hello !
You can actually test yourself if the network settings on MainRouter/Switch/WifiAP, using `Wireshark` on Windows and `tPacketCapture`(or similar apps) on mobile. The android <kbd>.pcap</kbd> you attached can be loaded into Wireshark on desktop and you can apply the above mentioned `filters` to check the network packets.

If I were you and I understood your network topography properly, i would just take a rj45 jack and connect my system directly, into WifiAP and test, into MainRouter and test. (You don’t need to turn on steamvr every time for testing, broadcast can be checked by Wireshark)

I don’t really think its frimware issue, there may be certain settings like `stop broadcast packets` (nomenclature differs with make), or routing tables or forwarding tables etc., similar settings on your network devices which may block the broadcast. If you can specify which devices are you using, make, model, etc, i can suggest you a more specific solutions :D

And yes, thanks in advance for testing PVR :)
