### ISSUE TITLE
No Output

### ISSUE THREAD

**Issue by TrickPlayzMC** [ShootingKing-AM/PhoneVR#33]
The Server is connected to my phone, but there is no display output on the phone

**Comment by thezofx** [comment]
Hello,

Can you share some logs and screenshot of what you are seeing on pc and Android as well.

Thanks for showing interest in this project.

**Comment by ShootingKing-AM** [comment]
@TrickPlayzMC Which logs to attach is mentions in [Readme.md - Issues](https://github.com/ShootingKing-AM/PhoneVR#issues).

**Comment by TrickPlayzMC** [comment]
Wait it's working now sorry
