### ISSUE TITLE
driver installation fail in non english windows versions

### ISSUE THREAD

**Issue by atesin** [ShootingKing-AM/PhoneVR#39]
error on "install-PhoneVR.bat" granting permissions on windows versions other than english

it doesn't found specified local user account and fails to grant installation directory permissions
for example, in my SPANISH windows installation i had to change line 35 (last commit 3 apr 2017) from

`icacls %instpath% /grant:r Everyone:(OI)(CI)F`

to 

`icacls %instpath% /grant:r Todos:(OI)(CI)F`

install.bat should be aware of OS localization, or use numeric local user account instead

Edit: i forgot to mention i am on windows 7 pro x64 spanish

**Comment by Day-OS** [comment]
That's strange. I'm using Windows 10, my native language is Portuguese and the .bat worked. But a solution for that would be great.

**Comment by ShootingKing-AM** [comment]
Oh! Intresting. I am anyway thinking of doing away with this installation method. I am thinking of asking users to driectly copy paste the driver directory into SteamVR folder of Steam. This .bat method is causing many permissions problems. I will have to test a little bit but i think newer versions of SteamVR automaticallty detects new drivers in its SteamVR/driver folder.

But anyways nice finding, i didnt think "Everyone" would be localized ^^"

**Comment by ShootingKing-AM** [comment]
@atesin I will close this issue after you test the new installation method :)

**Comment by atesin** [comment]
hi..  thanks for being confident

- i think until the new installation method is more manual is more reliable also
- i copied the folder as pvrserver folder inside steam dir and run steamvr as instructed, but pvr is not listed in steamvr devices
- so i suspected "vrpathreg.exe addriver ..." has something to do, so i run it manually and it SEEMS to me it is ok ("seems" because another problem i have)

so i suggest a register.bat file inside pvrserver folder like "..\..\bin\win64\vrpathreg.exe adddriver .\" or something like this

**Comment by ShootingKing-AM** [comment]
steamVR should auto-detect Phonevr driver with this new method. But I see some instances it's not. Ok I will add this as a extra check step.
