### ISSUE TITLE
Cannot save settings in app, connection is not working

### ISSUE THREAD

**Issue by KAJIKK** [ShootingKing-AM/PhoneVR#49]
<img src="https://user-images.githubusercontent.com/62884492/99539107-1d722400-29ae-11eb-8a29-9397f2c269dd.jpg" width="40%">

[logFromApp.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5560457/logFromApp.txt)
[pvrlog.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5560474/pvrlog.txt)
[vrserver.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5560477/vrserver.txt)
![SteamVr](https://user-images.githubusercontent.com/62884492/99540863-6034fb80-29b0-11eb-96a4-ec75d54a0fe8.png)

If I want to change settings in the app, I can't because there is no saving button and if I go back by hitting the android triangle button, it will just cancel all my changes. Also if I want to connect it to the SteamVr, it crashes and restarts and say the addon was blocked because of the crash. If I try to unblock it, it will just restart and do the same thing.

My phone is: Xoami POCO X3 NFC
Sorry for the pictures it is in the Czech language.

**Comment by ShootingKing-AM** [comment]
Are you using the latest version of PhoneVR ?

**Comment by KAJIKK** [comment]
I tested both the newest release and the previous builds

**Comment by ShootingKing-AM** [comment]
Please make sure not to type "," as decimal point. Motion to photon latency setting should be "0.020" and FOV "10.0". I will add an warning in the next version.

**Comment by KAJIKK** [comment]
Okay, we have progress. Now it saves the changed settings but and SteamVr is not crashing but now it says No headset found. Also, the app on phone sometimes closes itself but the phone is not saying it crashes. Another thing is interesting: If I save the changes in the app with "." and not "," it saves but if I open it again, there is "," on the decimal point. also, I never changed the Motion to photon latency and FOV until now. Maybe my phone is replacing that as an autocorrect but I am not sure.

**Comment by ShootingKing-AM** [comment]
Are you sure you have "Auto Start" and "Run in Background" permissions enabled for PhoneVR?

**Comment by KAJIKK** [comment]
![IMG_20201118_154918](https://user-images.githubusercontent.com/62884492/99546186-780f7e00-29b6-11eb-863a-e8231d5f64fa.jpg)
![IMG_20201118_154955](https://user-images.githubusercontent.com/62884492/99546205-7ba30500-29b6-11eb-91c5-450313e79cb1.jpg)
![IMG_20201118_154939](https://user-images.githubusercontent.com/62884492/99546210-7c3b9b80-29b6-11eb-8f39-425781dd2cbd.jpg)
![Error](https://user-images.githubusercontent.com/62884492/99546214-7d6cc880-29b6-11eb-84fe-5d959f9b70f7.png)

The "Run in background" I can't find anywhere

**Comment by ShootingKing-AM** [comment]
Is there anything new on the Logs or they are still the same after "," -> "." change ?

**Comment by KAJIKK** [comment]
Oh I have not noticed that
[NewlogFromApp.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5560913/NewlogFromApp.txt)

I also enabled the Debug mode

**Comment by thezofx** [comment]
.

**Comment by ShootingKing-AM** [comment]
@KAJIKK Does your issue still persist on latest Build ?

**Comment by KAJIKK** [comment]
I think no, because every time i have to manually change the "," to ".". But it saves when I changed it. I'm using the **beta 55** build.

**Comment by ShootingKing-AM** [comment]
This has been solved in #46. Try latest release, you don't need to bother about "," and "."s now :)

**Comment by KAJIKK** [comment]
Okay so, the "." is working now and i can now save the settings without need to change it but the connection is not working.
Using the **60 build**
OpenGL version: **3.2**

**Comment by ShootingKing-AM** [comment]
Hi @KAJIKK, Latest [beta0.2-62](https://github.com/ShootingKing-AM/PhoneVR/releases/tag/0.2-beta)(53) fixed this issue, can you re-check if its working and revert? If its still not working, please attach the logs.

Thanks.

**Comment by KAJIKK** [comment]
Hi, I am sorry but I failed again. I think a am doing something wrong.
I tried blank IP, manually enter IP and even changing the pairing port(on both devices) but still nothing.
Using beta-0.2-62 

[pvrlogANDROID.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5829605/pvrlogANDROID.txt)
[pvrlogPC.txt](https://github.com/ShootingKing-AM/PhoneVR/files/5829606/pvrlogPC.txt)

**Comment by ShootingKing-AM** [comment]
The logs are saying that Mobile is not able to connect to your PC via network. Can you try getting the .pcap files as specifed in ReadMe for [network issues](https://github.com/ShootingKing-AM/PhoneVR#issue--bug-reporting) ?

**Comment by KAJIKK** [comment]
[phonevrPCAP.zip](https://github.com/ShootingKing-AM/PhoneVR/files/5830579/phonevrPCAP.zip)
From the capture, I noticed the `not an ATH packet error, aborting`. Does ATH mean authorization?

**Comment by ShootingKing-AM** [comment]
ATH means, Apache Tribes Heartbeat Protocol (which PVR dosen't use).
Prima-facie, The packet is being received on desktop end from mobile, but its being modified (some extra data(padding) is being added to the packet end) which is not normal. 

Actual Android/PVR Source Packet:
```
0000   00 1a 11 00 00 02 00 1a 11 00 00 01 08 00 45 00   ..............E.
0010   00 24 a8 e3 40 00 40 11 c4 aa 0a 08 00 01 c0 a8   .$..@.@.........
0020   02 8a a4 c1 3e 73 00 10 66 e7 70 76 72 00 00 00   ....>s..f.pvr...
0030   06 00                                             ..
```

Desktop Packet:
```
0000   e4 54 e8 2f 75 dc 34 1c f0 30 37 e4 08 00 45 00   .T./u.4..07...E.
0010   00 24 38 ff 40 00 40 11 7b c9 c0 a8 02 26 c0 a8   .$8.@.@.{....&..
0020   02 8a b1 fc 3e 73 00 10 a0 e6 70 76 72 00 00 00   ....>s....pvr...
0030   06 00 00 00 00 00 00 00 f6 0f 9f 98               ............
```
The extra data on Line `0030` after `06 00` is what i am talking about.
Wireshark says the its from the Source, i.e from,
```
Source: XiaomiCo_30:37:e4 (34:1c:f0:30:37:e4)
Type: IPv4 (0x0800)
Padding: 000000000000f60f9f98
```

I hope .138 is the PC IP and .38 is the Mobile IP.
I am hoping this is a proprietrary feature of that specific Xiaomi device.
The PVR Server logs on the other side say that There is **no data** received even after waiting for 5secs, which is not actually true.

I can think about a few things,
1. I think there is a firewall blocking 15987(and 2 other ports) port on Windows Desktop end. or Blocking vrserver.exe program. <br/>
Try to disable any Antivirus/Firewall program. Also try to add Inbound rule (both TCP and UDP on the 3 ports) and Outbound rule (both TCP and UDP on 3 Ports) in Windows Firewall.

2. I think there are more multiple network adaptors on desktop and data is being received on Network adaptor X while PVR Server is listening to adaptor Y. <br/><br/>To verify this, can you tell me how many network adaptors are being used on desktop, and how is network connected between Mobile and Desktop. And on which network did you get the PCAP file from desktop (On this adaptor we are actually receiving the PVR data)

3. Maybe there is an unusual, excess network delay (>5 secs) for the packet to reach desktop.<br/><br/> You can increase the connection timeout on line `    "connection_timeout" : 5,` in `pvrsettings.json` file whose default location is `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\PVRServer`. You can increase to max of 10 (means 10 Secs) and see if its connects.

Sorry for making it a little complex ^^', you can ask me if you didnt understand anything written above.
Thanks !

**Comment by KAJIKK** [comment]
Finaly i get it working. My fault was that i allowed the firewall only for public networks. Sorry for that stupid mistake.
I hope that this thread helped everyone thet had same issue.
