### ISSUE TITLE
Shifted image on the phone

### ISSUE THREAD

**Issue by Mineplayerminer** [ShootingKing-AM/PhoneVR#82]
I have a problem that my VR output on the phone is shifted to the right. I think it is because of my camera cutout in the display. I have Redmi Note 9.

The result: 
![Screenshot_2021-08-11-10-12-59-959_viritualisres phonevr](https://user-images.githubusercontent.com/82465758/128995138-20501e92-def9-47f2-9afb-b36a6c8a94d7.jpg)

I have an option for the fullscreen in the MIUI settings, didn't work.

After enabling the fullscreen:
![Screenshot_2021-08-11-10-13-59-024_viritualisres phonevr](https://user-images.githubusercontent.com/82465758/128995264-26aac068-3ce1-4326-bb1b-932042188586.jpg)

I used Google Cardboard (2015 I/O). (With the QR code read in the Cardboard app)

Also I would like to add a function to change the lens shape on the phone screen, as the rectangular shape would have the best FOV.

**Comment by ShootingKing-AM** [comment]
Thanks for trying out PVR. Please attach all relavent logs - https://github.com/ShootingKing-AM/PhoneVR#issue--bug-reporting

**Comment by verypurple** [comment]
Hi! I wanted to give some more information!

I have Xiaomi Redmi Note 5 Pro with LineageOS and the same thing happens. The image is shifted when Fullscreen option in Android settings is turned on. I don't know why it doesn't work right, but when you enable it the app should use the entire screen, including the area under the notch normally occupied by the clock, battery indicator etc.

Thank you so much for your app, it's wonderful!

**Comment by Mineplayerminer** [comment]
> Hi! I wanted to give some more information!
> 
> I have Xiaomi Redmi Note 5 Pro with LineageOS and the same thing happens. The image is shifted when Fullscreen option in Android settings is turned on. I don't know why it doesn't work right, but when you enable it the app should use the entire screen, including the area under the notch normally occupied by the clock, battery indicator etc.
> 
> Thank you so much for your app, it's wonderful!

Using a custom ROM should NOT be a problem. But, seems like the whole Google Cardboard app wasn't designed for the phones with notches. At least, you can use a custom ROM, meanwhile, I'm stuck on the MIUI. Also, the App just crashes if you rotate the screen too many times while waiting for the SteamVR. I'll look for the logs.

**Comment by Mineplayerminer** [comment]
I hope the issue will be resolved in the next update. Until then, 👋😉. I also found out the problem persists only on the MIUI devices with any camera notch. (Whether it's a notch camera on a cutout)
