### ISSUE TITLE
No USB Tethering support

### ISSUE THREAD

**Issue by Mineplayerminer** [ShootingKing-AM/PhoneVR#89]
I have a problem. I have 2 routers, so I have a double NAT. That means I can't use the PhoneVR as my PC is connected to my main router and my phone to the Wi-Fi router. I tried disabling the DHCP and re-plugging it onto the LAN port. It didn't work. I would like to see the USB Tethering feature. It would decrease the latency and increase the picture quality. This was causing the SteamVR to crash after I manually typed the IP of my PC on the phone.

**Comment by Mineplayerminer** [comment]
I found out the Tethering is available but had to dig deeper into settings to set my phone as a Private network to make it discoverable and set the USB Tethering in the Developer settings on the MIUI.

**Comment by nobeltnium** [comment]
> I found out the Tethering is available but had to dig deeper into settings to set my phone as a Private network to make it discoverable and set the USB Tethering in the Developer settings on the MIUI.

Hey, i'm on MIUI also. How do you setup tethering as a private network? I'm trying to use my USB for connection but ALVR won't detect PhoneVR via tethering
